sudo: false
language: node_js
node_js:
- '13'
- '12'
- '11'
- '10'
matrix:
  fast_finish: true
branches:
  only:
    - master
notifications:
  email:
    on_success: never
cache:
  yarn: true
  directories:
  - node_modules

before_script: 'npm run linter'
script: 'npm run test && npm run update-harness && npm run harness'
after_script: 'npm run coverage'
